### ISSUE TITLE
Correcciones QMP - Entrega 1

### ISSUE THREAD

**Issue by PalumboN** [NicolasPabloW/tareasDDS#2]
Hola @NicolasPabloW, muy buena tu entrega, te dejo algunos comentarios que fui anotando:

- Muy bien comunicado el diseño.
- Por más que declares un constructor pueden venir datos en null, así que para el sexto requerimiento de todas formas habría que validar que los valores no sean nulos.
- Para el color secundario, si bien es opcional, el agregar un setter hace que tu objeto pueda _mutar_ esa propiedad, que quizá es algo que no nos interese (para el resto de los atributos sería inmutable, y eso está bien, porque una vez que hacemos la validación no querríamos que cambie). Se podría recibir un null por constructor (y no checkearlo) o tener 2 constructores y que uno delegue en el otro.
- Bien explicada la validación de Categoría y Tipo. (Otra alternativa sería al revés, que el tipo conozca a qué categoría pertenece, y que la prenda directamente la calcule a partir de su tipo. Tu alternativa también es válida, solamente no quería dejar de comentarla).
- Bien **argumentado** los tipos de datos String :clap: . Hay que ver si los materiales y tipos disponibles son realmente amplios, pero bien justificada tu decisión.
- Me gusta cómo modelaste el color.

**Comment by NicolasPabloW** [comment]
Perdon la tadanza , gracias por la devolucion.
